version: "3.8"
services:
  backend:
    command: >
      sh -c
      "python manage.py collectstatic --noinput && 
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    build: ./backend
    stdin_open: true
    tty: true
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine
    env_file:
      - ./backend/.env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: