# Generated by Django 4.2.6 on 2024-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloze_tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clozetest",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
