# Generated by Django 4.2.6 on 2024-08-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloze_tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clozetest",
            name="publish_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
